more robust start/stop servers: detects multiple launches

diff --git a/server/start_compute_server b/server/start_compute_server
--- a/server/start_compute_server
+++ b/server/start_compute_server
@@ -19,6 +19,13 @@ LOG_DIR=$VAR_DIR/log
 COMPUTE_CONFIG=$LIB_DIR/ar_compute.conf
 
 
+procs=`ps aux |grep ar_computed.py |grep python`
+if [ -n "$procs" ]; then
+    echo 'Error: another compute server may be running.'
+    exit 1
+fi
+
+
 mkdir -p $LOG_DIR
 
 ARG_URL=$(     [[ -z "$SERVER_URL"   ]] && echo "" || echo "--server $SERVER_URL")
diff --git a/server/start_control_server b/server/start_control_server
--- a/server/start_control_server
+++ b/server/start_control_server
@@ -14,6 +14,13 @@ LOG_DIR=$VAR_DIR/log
 CONTROL_CONFIG=$LIB_DIR/arast.conf
 
 
+procs=`ps aux |grep arastd.py |grep python`
+if [ -n "$procs" ]; then
+    echo 'Error: another control server may be running.'
+    exit 1
+fi
+
+
 mkdir -p $LOG_DIR
 
 args=( --config $CONTROL_CONFIG
